# Generated by Django 5.1.1 on 2024-09-29 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='project_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_category', models.CharField(choices=[('Science & Technology', 'School of Science & Technology'), ('Business', 'School of Business'), ('Education', 'School of Education'), ('Health Sciences', 'School of Health Sciences'), ('Natural Sciences', 'School of Natural Sciences'), ('Social Sciences', 'School of Social Sciences'), ('Theology & Religious Studies', 'School of Theology & Religious Studies'), ('Agriculture', 'School of Agriculture & Applied Sciences')], max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('github_link', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('image_sample', models.ImageField(blank=True, default='default.png', upload_to='project_images/')),
                ('benefit', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projectinformation')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projectinformation')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
