# Generated by Django 5.1.1 on 2024-10-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_projectdetails_image_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='author',
            new_name='user',
        ),
    ]
